/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2018-09-06 02:42:00 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@127.0.0.1/test -t documents -s test
 *
 */


export namespace documentsFields {
    export type id = number;
    export type group_id = number;
    export type group_id2 = number;
    export type date_added = Date;
    export type title = string;
    export type content = string;

}

export interface documents {
    id: documentsFields.id;
    group_id: documentsFields.group_id;
    group_id2: documentsFields.group_id2;
    date_added: documentsFields.date_added;
    title: documentsFields.title;
    content: documentsFields.content;

}
